config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  resources :projects do
    resources :slides
  end
  get 'reactdnd', to: 'pages#reactdnd'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :song, :member_list, :slide_count, presence: true
  has_many :slides
end

app/models/slide.rb
class Slide < ApplicationRecord
  validates :timestamp, presence: true
  has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def reactdnd
    
  end
  
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destory]
  def index
    @projects = Project.all
  end

  def show
    # code
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:success] = 'Object successfully created'
      redirect_to @project
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      @project.save!
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to @project
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :song, :member_list, :slide_count)
  end

  def find_slide
    @slide = Slide.find(params[:slide_id])
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :find_slide, only: [:show, :edit, :update, :destroy]
  before_action :find_project, only: [:new, :create]
  def index
    @slides = Slide.all
  end

  def show
  end

  def new
    @slide = Slide.new
  end

  def create
    @slide = Slide.new(slide_params)
    @slide.project_id = @project.id
    if @slide.save
      @slide.save!
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit
    # code
  end

  def update
    @slide.update(slide_params)
    redirect_to @slide
  end

  def destroy
    @slide.destroy
    redirect_to slides_path
  end

  private

  def slide_params
    params.require(:slide).permit(:timestamp)
  end

  def find_slide
    @slide = Slide.find(params[:id])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DGC Formation Maker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="site-banner">
        <div class="my-projects">
          <h1 class="banner-text">DGC Formation Maker</h1>
        </div>
      </div>
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

app/views/pages/reactdnd.html.erb
<div id="app"></div>
<%= link_to "Back", root_path %>

app/views/projects/edit.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :song %>
  <%= f.input :member_list %>
  <%= f.input :slide_count %>
  <%= f.button :submit %>
<% end %>
<div class="link">
  <%= link_to "Cancel", :back %>
</div>

app/views/projects/index.html.erb
<div class="my-projects">
  <h1>My Projects</h1>
  <div class="project-area">
    <ul class="project-list">
        <% @projects.each do |project| %>
          <li class="project-item">
            <div class="project-card">
              <%= link_to project.name, project_path(project) %>
            </div>
          </li>
        <% end %>
    </ul>
  </div>
  <div class="links">
    <%= link_to "Create a new project", new_project_path, class: "create-project-button" %>
  </div>
</div>

app/views/projects/new.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :song %>
  <%= f.input :member_list %>
  <%= f.input :slide_count %>
  <%= f.button :submit %>
<% end %>
<div class="links">
  <%= link_to "Cancel", :back %>
</div>

app/views/projects/show.html.erb
<div class="project-info">
  Project name: <%= @project.name %>
  <br>
  Song name: <%= @project.song %>
  <br>
  Member List: <%= @project.member_list %>
  <br>
  Slide count: <%= @project.slide_count %>
  <br>
  Slide list:
  <% @project.slides.each do |item| %>
    <%= link_to "#{item.timestamp}", project_slide_path(@project.slides) %>
  <% end %>
</div>
<div class="links">
  <%= link_to "New Slide", new_project_slide_path(@project, @slide) %>
  <br>
  <%= link_to "Edit", edit_project_path(@project) %>
  <br>
  <%= link_to project_path(@project), method: :delete, data: { confirm: "Are you sure?" } do %>
    Delete
  <% end %>
  <br>
  <%= link_to "Return to project list", root_path %>
</div>

app/views/slides/index.html.erb
<div class="container">
  <ul>
    <h3>Slides Index</h3>
    <% @slides.each do |slide| %>
      <li>
        <%= slide.timestamp %>
        <br>
      </li>
    <% end %>
  </ul>
</div>

app/views/slides/new.html.erb
<%= simple_form_for [@project, @slide] do |f| %>
  <%= f.input :timestamp %>
  <%= f.button :submit %>
<% end %>
<div class="links">
  <%= link_to "Cancel", :back %>
</div>